name: Warehouse App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create Git Tag and Push
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)  # Tag format like 20250129010101-abc123
          git tag "$VERSION"
          git push origin "$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*  # Upload all files in the dist folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
